AllCops:
  Exclude:
    - 'fixtures/**/*'
Metrics/AbcSize:
  Severity: warning
Metrics/CyclomaticComplexity:
  Severity: warning
Metrics/LineLength:
  Severity: warning
Metrics/ModuleLength:
  Severity: warning
Metrics/PerceivedComplexity:
  Severity: warning
