rspec_options = {
  cmd: 'bundle exec rspec',
  run_all: { cmd: 'bundle exec rspec -P spec/unit/*_spec.rb' }
}

guard :rspec, rspec_options do
  require 'guard/rspec/dsl'
  dsl = Guard::RSpec::Dsl.new(self)

  # RSpec files
  rspec = dsl.rspec
  watch(rspec.spec_helper) { rspec.spec_dir }
  watch(rspec.spec_support) { rspec.spec_dir }
  watch(rspec.spec_files)

  # Ruby files
  ruby = dsl.ruby
  dsl.watch_spec_files_for(ruby.lib_files)

  # Rake files
  watch(%r{lib/tasks/.+\.rake})
end

# vi:ft=ruby
